root -l -q AddDivideMultiply.C++ ../../steerings/ROCpt.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCraw.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCpruned.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCtrimmed.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCsoftdrop.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCmet.steer bsefficiency
root -l -q AddDivideMultiply.C++ ../../steerings/ROCpt.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/ROCraw.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/ROCpruned.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/ROCtrimmed.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/ROCsoftdrop.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/ROCmet.steer merge
root -l -q AddDivideMultiply.C++ ../../steerings/pteff.steer distrandeff
root -l -q AddDivideMultiply.C++ ../../steerings/mean.steer countmean
